### PR TITLE
Add ethers file to support naming ruuvitags

### PR DESCRIPTION
**Pull request by decke**
This feature allows naming ruuvitags which is used in the MQTT topic.

A file called `ethers` is used for the mapping between bluetooth address and name so the format is the same as /etc/ethers commonly used for dhcpd. bluetooth address in ethers is not case sensitive.

For backwards compatibility the bluetooth address is used if no matching entry was found.

### CODE REVIEW

**Comment by decke** [comment]
ping

**Comment by decke** [comment]
Any comment about this PR positive or negative?

**Comment by jarijokinen** [comment]
Great additions, thanks.

Let me know if you are going to work more on this project and like to take over it, I'd be happy to archive my repo and add a link to yours in the README. Or add you as a collaborator here so you don't have to wait approvals from me. I don't personally need the esp32 gateway anymore (bought the official ruuvitag gw), and thus probably won't add new features to this project in the future by myself. I don't mind reviewing the PRs though, but it just takes some time sometimes.

**Comment by decke** [comment]
Thanks for merging!

For the moment I do not plan to implement any new features or rework anything because it suits my needs very well and it's simple and well designed! If you want I can help maintain it since I think it's not very time consuming and I am actively using it which will not change anytime soon. But for me it's also fine to push the patches like I did before.

Right now I am using ruuvi-gw on a ESP32 covering my whole house with 7 ruuvitags and feed the data to a local mqtt. Actually it replaced a RPI Zero 2W + python to mqtt script which did the same but was unstable (because of bluetooth firmware bugs) so it required frequent reboots and consumed much more power.

Some days ago I also used your project as a starting point for [decke/temp2mqtt-esp32](https://github.com/decke/temp2mqtt-esp32) which is a small ESP32 + DS18B20 temperature gateway for my boiler.

**Comment by jarijokinen** [comment]
Thanks, glad to hear that you've found it useful. The low power consumption was the main reason for starting this project, as  I planned to use this battery-powered on a boat and a campervan. But never got that far, and never actually measured how long can it run on a battery (sold the boat and now monitoring the van only when it's connected to the mains power).

**Pull request merged**
